export const STATE_REGS = {
  AL: { name:"Alabama", infant:6, toddler:8, preschool:12, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:24, inspPerYear:1, directorReq:"HS diploma + CDA or 12 ECE credit hours (DHR 660-5-26-.05)", teacherReq:"High school diploma or GED (DHR 660-5-26-.05)", qrs:"Alabama Quality STARS", agency:"AL Dept of Human Resources (DHR) — Child Care Services", agencyPhone:"(334) 242-1425", agencyWebsite:"dhr.alabama.gov/childcare", citation:"AL DHR Reg. Chapter 660-5-26", enablingStatute:"Code of Alabama §38-7-1 et seq.", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State (ALEA) + FBI fingerprint", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", immExemptionStatute:"AL Code §22-11A-14", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", mandatedReporterStatute:"AL Code §26-14-3", workforceRegistry:"Alabama Quality STARS (voluntary tracking)", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"},
    refs:{
      ratios:"DHR 660-5-26-.07",
      indoorSqft:"DHR 660-5-26-.10",
      outdoorSqft:"DHR 660-5-26-.10",
      trainingHrs:"DHR 660-5-26-.08",
      directorReq:"DHR 660-5-26-.05",
      teacherReq:"DHR 660-5-26-.05",
      bgCheckType:"DHR 660-5-26-.06",
      staffPhysical:"DHR 660-5-26-.06",
      tbTestReq:"DHR 660-5-26-.06",
      cprRenewal:"DHR 660-5-26-.08",
      immExemptions:"AL Code §22-11A-14",
      mandatedReporter:"AL Code §26-14-3",
      fireDrill:"DHR 660-5-26-.11",
      tornadoDrill:"DHR 660-5-26-.11",
      lockdownDrill:"DHR 660-5-26-.11",
      recordRetention:"DHR 660-5-26-.12",
      hotWaterMax:"DHR 660-5-26-.10",
      toiletRatio:"DHR 660-5-26-.10",
      fencingMin:"DHR 660-5-26-.10",
      inspections:"DHR 660-5-26-.02"
    } },
  AZ: { name:"Arizona", infant:4, toddler:6, preschool:13, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1,
    directorReq:"18 ECE credit hours + 3 years experience (AAC R9-5)",
    teacherReq:"HS diploma + 6 ECE credit hours or CDA (AAC R9-5)",
    qrs:"AzQRIS", agency:"AZ Dept of Health Services (ADHS) — Division of Licensing",
    agencyPhone:"(602) 364-2539", agencyWebsite:"azdhs.gov/licensing",
    citation:"AAC R9-5", enablingStatute:"ARS §36-881 et seq.",
    insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"},
    rules:{
      fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes",
      qrisType:"Voluntary", bgCheckType:"State (DPS) + FBI fingerprint",
      tbTestReq:"Initial only", cprRenewal:"2 years",
      immExemptions:"Medical + Religious + Philosophical",
      annualImmReporting:"Yes", recordRetention:"1 year",
      tornadoDrill:"Required (plan only)", lockdownDrill:"2x/year",
      coDetector:"Required", mandatedReporterRenewal:"No renewal required",
      workforceRegistry:"No state workforce registry",
      staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft",
      // Inspection report structure (AAC R9-5)
      inspectionTypes:["Routine","Complaint","Follow-up"],
      inspectionCiteFormat:"AAC R9-5 — [Section name]",
      violationSeverity:["Immediate","Serious","Technical"],
    },
    // CORRECTION APPLIED 14 May 2026: infant ratio corrected 1:5 → 1:4 (AAC R9-5)
    refs:{
      ratios:"AAC R9-5 — Ratios",
      indoorSqft:"AAC R9-5 — Physical Environment",
      outdoorSqft:"AAC R9-5 — Physical Environment",
      trainingHrs:"AAC R9-5 — Training",
      directorReq:"AAC R9-5 — Staff Qualifications",
      teacherReq:"AAC R9-5 — Staff Qualifications",
      bgCheckType:"AAC R9-5 — Background Checks (AZ Dept of Public Safety (DPS) + FBI)",
      staffPhysical:"AAC R9-5 — Staff Health",
      tbTestReq:"AAC R9-5 — Staff Health",
      cprRenewal:"AAC R9-5 — Staff Health",
      immExemptions:"AAC R9-5 — Health / state statute",
      mandatedReporter:"AAC R9-5 / state statute (No renewal)",
      fireDrill:"AAC R9-5 — Safety",
      tornadoDrill:"AAC R9-5 — Safety",
      lockdownDrill:"AAC R9-5 — Safety",
      recordRetention:"AAC R9-5 — Records",
      hotWaterMax:"AAC R9-5 — Physical Environment",
      toiletRatio:"AAC R9-5 — Physical Environment",
      fencingMin:"AAC R9-5 — Physical Environment",
      inspections:"AAC R9-5 — Licensing",
    } },
  BC: { name:"British Columbia", infant:4, toddler:4, preschool:8, schoolAge:15, indoorSqft:33, outdoorSqft:66, trainingHrs:40, inspPerYear:1, directorReq:"ECE Certificate + 500 hours supervised practice", teacherReq:"ECE Certificate (BC)", qrs:"BC Child Care Quality Assurance", agency:"BC Ministry of Children & Family Development", agencyPhone:"1-877-387-7027", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F (43°C)", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"RCMP Criminal Record Check", tbTestReq:"Initial only", cprRenewal:"3 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"ECE Registry (BC)", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  CA: { name:"California", infant:4, toddler:6, preschool:12, schoolAge:14, indoorSqft:35, outdoorSqft:75, trainingHrs:16, inspPerYear:1,
    directorReq:"AA in ECE or related field + 2 years teaching experience (CCR Title 22 §101215.1)",
    teacherReq:"12 ECE/CD units including core courses (CCR Title 22 §101216.1)",
    qrs:"Quality Counts California (QCC)", agency:"CA Dept of Social Services — Community Care Licensing Division", agencyPhone:"(916) 651-6040", insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"},
    rules:{
      fireDrillFreq:"Monthly",
      hotWaterMax:"110°F",
      fireSafetyTraining:"Yes",
      qrisType:"Voluntary",
      bgCheckType:"Live Scan — DOJ + FBI",
      tbTestReq:"Risk-based assessment",
      cprRenewal:"2 years",
      immExemptions:"Medical only (SB 277 — HSC §120335)",
      annualImmReporting:"Yes",
      recordRetention:"3 years",
      tornadoDrill:"Not required",
      lockdownDrill:"2x/year",
      coDetector:"Required",
      mandatedReporterRenewal:"Every 2 years (mandatedreporterca.com — HSC §11165.7)",
      workforceRegistry:"CA ECE Workforce Registry",
      staffPhysical:"Required at hire",
      toiletRatio:"1:15 (preschool) / 1:30 (school-age)",
      minFencingHeight:"4 ft"
    },
    refs:{
      ratios:"CCR Title 22 §101216.3",
      indoorSqft:"CCR Title 22 §101238.3",
      outdoorSqft:"CCR Title 22 §101238.2",
      trainingHrs:"HSC §1596.866",
      directorReq:"CCR Title 22 §101215.1",
      teacherReq:"CCR Title 22 §101216.1",
      bgCheckType:"CCR Title 22 §101170",
      immExemptions:"HSC §120335 (SB 277)",
      mandatedReporter:"HSC §11165.7",
      personnelRecords:"CCR Title 22 §101217",
      childRecords:"CCR Title 22 §101221",
      hotWaterMax:"CCR Title 22 §101239",
      toiletRatio:"CCR Title 22 §101239",
      smokingProhibition:"CCR Title 22 §101231",
      coDetector:"HSC §13261",
      fireDrill:"CCR Title 22 §101238"
    }
  },

  CO: { name:"Colorado",
    // Infant split at 6 months — corrected 14 May 2026 (§7.702.1(A))
    infant:4, infantLabel:"Birth–6 months (1:4) | 6–15 months (1:5)",
    infantTier2:5, infantTier2Ages:"6–15 months",
    toddler:5, preschool:10, schoolAge:15,
    indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1,
    directorReq:"BA in ECE or related field + 1 yr (or AA in ECE + 3 yrs, or CDA + 5 yrs) (12 CCR 2509-8 §7.712)",
    teacherReq:"HS diploma + CDA or 12 ECE credit hours (§7.712)",
    qrs:"Colorado Shines", qrsScale:"1–5 stars",
    agency:"CO Dept of Human Services (CDHS) — Division of Early Care and Learning",
    agencyPhone:"(303) 866-5958", agencyWebsite:"cdhs.colorado.gov/childcare",
    citation:"12 CCR 2509-8", enablingStatute:"CRS §26-6-100 et seq.",
    insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"},
    rules:{
      fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes",
      qrisType:"Voluntary", bgCheckType:"State (CBI) + FBI fingerprint",
      tbTestReq:"Initial only", cprRenewal:"2 years",
      immExemptions:"Medical + Religious + Philosophical",
      immExemptionStatute:"CRS §25-4-903",
      annualImmReporting:"Yes", recordRetention:"1 year",
      tornadoDrill:"2x/year", lockdownDrill:"2x/year",
      coDetector:"Required", coDetectorStatute:"CRS §38-45-101",
      mandatedReporterRenewal:"No renewal required",
      mandatedReporterStatute:"CRS §19-3-304",
      workforceRegistry:"Colorado Shines Registry (CDHS)",
      staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft",
      // Colorado-specific: infant age tracked to month for tier calculation
      infantRatioNote:"Track each infant DOB to month — under 6mo requires 1:4 even if group ratio appears compliant",
      // Inspection report structure
      inspectionTypes:["Supervisory","Announced","Unannounced","Complaint","Follow-up"],
      inspectionCiteFormat:"2.XXX.X — General Rules / Center Rules / Special Activity Rules",
      inspectionAgency:"Colorado Department of Early Childhood",
      inspectionAgencyAddress:"710 S. Ash Street, Denver, CO 80246",
      inspectionAgencyPhone:"303-866-5948",
      inspectionAgencyFax:"303-866-4453",
      inspectionAgencyWebsite:"cdec.colorado.gov",
      inspectionDocTitle:"Report of Inspection (ROI)",
      inspectionROIFormat:"ROI ID: [LicenseNumber]-[MMDDYYYY]",
      inspectionSignatureNote:"Signature acknowledges receipt only — not guilt. Appeal rights per §26.5-5-314(5) CRS",
      inspectionCorrectionDeadline:"Immediate for safety violations; 30 days standard; written verification to agency",
      inspectionAppealStatute:"§26.5-5-314(5) C.R.S.",
      inspectionEnforcementStatute:"§26.5-5-317(1-9) C.R.S.",
      inspectionFeedbackURL:"https://cdec.colorado.gov/",
      violationSeverity:["Immediate — corrected at time of visit","Correct immediately","Standard deadline"],
      // Violation categories from real ROI (Lionheart RCCO — 10/29/2025)
      commonViolationCategories:[
        "Sharp tools accessible to children (2.229.H)",
        "Choke hazards accessible to children under 3 (2.229.L)",
        "Standard precautions training expired (2.213.B — annual renewal)",
        "Safe sleep training expired — infant staff (2.213.C — annual renewal)",
        "Child abuse prevention training expired (2.213.G — annual renewal)",
        "Emergency/disaster preparedness training missing (2.133.A)",
        "Items labeled keep-out-of-reach accessible (2.229.C)",
        "Room capacity exceeded (2.217.A.15.d)",
        "Resilient surfacing below minimum — climbing equipment (2.230.C.1.a)",
        "Health statements missing or expired — staff (2.212.G — annual renewal)",
        "Toddler room not physically separated from other ages (2.233.C.1)",
        "Fire inspection expired (2.122.A — required every 2 years)",
      ],
      // Colorado-specific: 3 rule sets apply
      rulesSets:["Center Rules","General Rules","Special Activity Rules"],
      inspectionNote:"Violations may affect Colorado Shines star rating. Subsequent violations of same type may be considered willful.",
    },
    refs:{
      ratios:"12 CCR 2509-8 §7.702.1",
      infantTier:"12 CCR 2509-8 §7.702.1(A) — split at 6 months",
      toddlerRatio:"§7.702.1(B)",
      preschoolRatio:"§7.702.1(C)",
      schoolAgeRatio:"§7.702.1(D)",
      indoorSqft:"12 CCR 2509-8 §7.706",
      outdoorSqft:"§7.706",
      hotWaterMax:"§7.706",
      toiletRatio:"§7.706",
      fencingMin:"§7.706",
      trainingHrs:"12 CCR 2509-8 §7.712",
      directorReq:"§7.712",
      teacherReq:"§7.712",
      cprRenewal:"§7.712",
      staffPhysical:"12 CCR 2509-8 §7.711",
      tbTestReq:"§7.711",
      bgCheckType:"CRS §26-6-104 (CBI + FBI)",
      immExemptions:"CRS §25-4-903",
      mandatedReporter:"CRS §19-3-304",
      coDetector:"CRS §38-45-101",
      fireDrill:"12 CCR 2509-8 §7.709",
      tornadoDrill:"§7.709",
      lockdownDrill:"§7.709",
      recordRetention:"12 CCR 2509-8 §7.714",
      inspections:"CDHS Division of Early Care and Learning",
      standardPrecautions:"12 CCR 2509-8 §2.213.B — annual renewal required",
      safeSleepTraining:"12 CCR 2509-8 §2.213.C — required for all infant staff, annual renewal",
      childAbuseTraining:"12 CCR 2509-8 §2.213.G — required within 30 days of hire, annual renewal",
      emergencyPreparednessTraining:"12 CCR 2509-8 §2.133.A — required prior to working with children",
      roomCapacity:"12 CCR 2509-8 §2.217.A.15.d — licensed room capacity must not be exceeded",
      chokeHazards:"12 CCR 2509-8 §2.229.L — areas accessible to under-3s must be free of choke hazards",
      sharpToolStorage:"12 CCR 2509-8 §2.229.H — sharp tools inaccessible to children",
      keepOutOfReach:"12 CCR 2509-8 §2.229.C — items labeled keep-out-of-reach must be inaccessible",
      resilientSurfacing:"12 CCR 2509-8 §2.230.C.1.a — min 6 inches for climbing equipment 18+ inches",
      toddlerRoomSeparation:"12 CCR 2509-8 §2.233.C.1 — toddler rooms physically separated by 8ft walls + full doors",
      fireInspection:"12 CCR 2509-8 §2.122.A — required every 2 years from local fire dept + health dept",
      staffHealthStatement:"12 CCR 2509-8 §2.212.G — required within 6 months prior or 30 days after hire; annual self-reported renewal",
    } },
  CT: { name:"Connecticut", infant:4, toddler:4, preschool:10, schoolAge:10, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"BA in ECE or related field + 2 years supervisory experience", teacherReq:"60 college credits including 12 in ECE, or CDA", qrs:"CT QRIS", agency:"CT Office of Early Childhood", agencyPhone:"(860) 500-4450", insurance:"Required — min $100,000", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical only", annualImmReporting:"Yes", recordRetention:"3 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"3 years", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  DC: {
    name:"District of Columbia",
    infant:3,
    toddlerTier1:4, toddlerTier1Ages:"12–24 months",
    toddlerTier2:6, toddlerTier2Ages:"24–36 months",
    preschoolTier1:8, preschoolTier1Ages:"3–4 years",
    preschoolTier2:10, preschoolTier2Ages:"4–5 years",
    schoolAgeTier1:12, schoolAgeTier1Ages:"Kindergarten / 5 years",
    schoolAgeTier2:15, schoolAgeTier2Ages:"6 years and older",
    indoorSqft:35, indoorSqftInfant:50,
    outdoorSqft:75, trainingHrs:40, inspPerYear:2,
    directorReq:"BA in ECE, child development, or related field + 3 years experience in licensed child care (including 1 year supervisory) (29 DCMR §93-4(a))",
    teacherReq:"AA in ECE or child development, or 60 college credits including 12 in ECE/CD + 1 year experience (29 DCMR §93-4(b))",
    qrs:"DC Quality Stars", agency:"DC Office of the State Superintendent of Education (OSSE)", agencyPhone:"(202) 727-8300", insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"},
    rules:{
      fireDrillFreq:"Monthly",
      hotWaterMax:"100°F",  // CORRECTION: DC §122.18 specifies 100°F (not 110°F like most states)
      fireSafetyTraining:"Yes",
      qrisType:"Required for subsidy",
      bgCheckType:"FBI + DC MPD + CANR (Child Abuse & Neglect Registry)",
      tbTestReq:"At hire + renewal every 2 years (29 DCMR §93-5(a))",
      cprRenewal:"2 years",
      immExemptions:"Medical only (DC Code §38-506)",
      annualImmReporting:"Yes",
      recordRetention:"3 years",
      tornadoDrill:"Not required",
      lockdownDrill:"2x/year",
      coDetector:"Required",
      mandatedReporterRenewal:"Every 2 years (DC Code §4-1321.02)",
      workforceRegistry:"DC Child Care Connections (DC OSSE)",
      staffPhysical:"Required at hire + annual renewal (29 DCMR §93-5(a) + §131.5(b))",
      staffPhysicalNote:"DC requires BOTH initial physical (§131.5(a)) AND annual renewal (§131.5(b)) — differs from most states",
      toiletRatio:"1:10",
      minFencingHeight:"4 ft",
      // DC-specific requirements from Annual Inspection Report
      foodProtectionManager:"Required — at least 1 certified Food Protection Manager on site (§155.4)",
      foodProtectionManagerNote:"Failure to have certified Food Protection Manager is a citable deficiency (§155.4) — DC-specific",
      smokeDetectorTesting:"Quarterly — written log required (§122.23)",
      coDetectorTesting:"Every 6 months — written log required (§122.22)",
      emergencyDrills:"2x/year at varying times of day (§148.1)",
      emergencyDrillLogRetention:"5 years (§148.2)",
      preServiceTraining30Days:"Health and safety standards within 30 days of hire (§139.2)",
      preServiceTraining90Days:"Additional pre-service training within 90 days of hire (§139.3)",
      criticalHealthSafetyTraining:"Required before unsupervised care (§139.4)",
      licenseDisplay:"License, permits, inspection reports must be displayed in one central area (§129.2)",
      insuranceDisplay:"Current liability insurance documentation on site (§129.4)",
      // Inspection report structure
      inspectionTypes:["Annual","Complaint","Follow-up","Re-inspection"],
      inspectionDocTitle:"Annual Inspection Report",
      inspectionAgency:"DC Office of the State Superintendent of Education (OSSE)",
      inspectionPortal:"My Child Care DC — mychildcaredc.dc.gov",
      inspectionLicenseFormat:"CDC-XXXXXX",
      inspectionCiteFormat:"§XXX.X (DCMR numbered sections)",
      inspectionStatusOptions:["Met","Not Applicable","Follow-up Met","Non-Compliance"],
      inspectionDeficiencyFormat:"Deficiency Date | Code | Type | Status | Corrective Action | Correction Date",
      inspectionSummaryDoc:"Statement of Deficiency (SOD) + Plan of Correction (POC) issued at completion",
      inspectionDeficiencyCategories:["Administrative records","Recordkeeping for staff","Health and safety"],
      inspectionNoImminentDangerNote:"Inspection summary notes whether any deficiency presented imminent danger",
      inspectionCorrectionDeadline:"Typically corrected within weeks — date specified per deficiency",
    },
    refs:{
      ratios:"29 DCMR §93-9(a)–(g)",
      indoorSqft:"29 DCMR §93-8(a)–(b)",
      outdoorSqft:"29 DCMR §93-8(c)",
      trainingHrs:"29 DCMR §93-5(c)",
      directorReq:"29 DCMR §93-4(a)",
      teacherReq:"29 DCMR §93-4(b)",
      bgCheckType:"29 DCMR §93-6 (FBI + DC MPD + CANR)",
      immExemptions:"DC Code §38-506 (medical only)",
      mandatedReporter:"DC Code §4-1321.02 (at hire + 2-yr renewal)",
      personnelRecords:"29 DCMR §93-7(d)",
      childRecords:"29 DCMR §93-7(d)",
      hotWaterMax:"29 DCMR §93-8(e)",
      toiletRatio:"29 DCMR §93-8(d)",
      tbTestReq:"29 DCMR §93-5(a) (initial + 2-yr renewal)",
      coDetector:"DC Code §6-751.01; 29 DCMR §93-8",
      fireDrill:"29 DCMR §93-10(a)",
      lockdownDrill:"29 DCMR §93-10(b)",
      fencing:"29 DCMR §93-8(c)",
      insurance:"29 DCMR §93-3",
      inspPerYear:"29 DCMR §93-2",
      // From real DC inspection report — Takoma Children's Center (CDC-909397)
      foodProtectionManager:"§155.4 — Failure to have Food Protection Manager is citable",
      staffPhysicalAnnual:"§131.5(b) — Annual physical renewal (DC only)",
      staffPhysicalInitial:"§131.5(a) — Pre-employment physical within 12 months",
      communicableDiseaseExclusion:"§118.4(a) per 5-E DCMR §§1023.1, 1023.5, 1023.9",
      licenseCapacityCompliance:"§118.1",
      ratioSupervision:"§120.4–120.5, §121.2",
      exitRequirements:"§122.3(a)–(c)",
      disabilityAccess:"§122.10 (ADA + Section 504)",
      smokeDetectors:"§122.23 — quarterly testing log required",
      coDetectors:"§122.22 — 6-month testing log required (if gas service)",
      emergencyDrills:"§148.1–148.2 — 2x/year, log retained 5 years",
      fingerPinchProtection:"§124.8",
      outdoorGateLatching:"§125.8 — positive self-latching at 4ft or preschool-proof",
      resilientSurfacing:"§125.13",
      foodServiceCompliance:"§155.1 — DC Food Code Title 25-A DCMR",
      cprFirstAid:"§150.1 — all staff, age-appropriate certification",
      preServiceTraining:"§139.2–139.4 — 30 days + 90 days + critical before unsupervised",
      recordsDisplay:"§129.2 — all permits/inspections in one central area",
      liabilityInsuranceOnFile:"§129.4",
    }
  },
  FL: {
    name:"Florida",
    infant:4, toddler:6,
    preschoolTier1:11, preschoolTier1Ages:"2–3 years",
    preschoolTier2:15, preschoolTier2Ages:"3–4 years",
    preschoolTier3:20, preschoolTier3Ages:"4–5 years",
    schoolAge:25,
    indoorSqft:35, outdoorSqft:45, trainingHrs:10, inspPerYear:2,
    directorReq:"HS diploma + Florida Director Credential (FDC) + 40-hr DCF-approved introductory training (FAC §65C-22.001(4)(b))",
    teacherReq:"HS diploma + 40-hr DCF-approved introductory training within 90 days of hire (FAC §65C-22.001(4)(a))",
    qrs:"Gold Seal Quality Care", agency:"FL Dept of Children and Families", agencyPhone:"(888) 352-2842", insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"},
    rules:{
      fireDrillFreq:"Monthly",
      hotWaterMax:"110°F",
      fireSafetyTraining:"Yes",
      qrisType:"Voluntary",
      bgCheckType:"Level 2 — FDLE + FBI (VECHS)",
      tbTestReq:"Initial only (risk-based)",
      cprRenewal:"2 years",
      immExemptions:"Medical + Religious (FS §1003.22)",
      annualImmReporting:"Yes",
      recordRetention:"2 years",
      tornadoDrill:"Monthly",
      lockdownDrill:"2x/year",
      coDetector:"Required",
      mandatedReporterRenewal:"No renewal required (FS §39.203 — one-time at hire)",
      workforceRegistry:"FL ELPD Registry (FL Office of Early Learning — FS §1002.82)",
      staffPhysical:"Required within 30 days of hire",
      toiletRatio:"1:15",
      minFencingHeight:"4 ft"
    },
    refs:{
      ratios:"FAC §65C-22.001(5)(a)",
      indoorSqft:"FAC §65C-22.003(1)(a)",
      outdoorSqft:"FAC §65C-22.003(2)(a)",
      trainingHrs:"FAC §65C-22.001(4)(a)",
      directorReq:"FAC §65C-22.001(4)(b)",
      teacherReq:"FAC §65C-22.001(4)(a)",
      bgCheckType:"FAC §65C-22.006(1)(a); FS §435.04",
      immExemptions:"FS §1003.22",
      mandatedReporter:"FS §39.203; FAC §65C-22.001(4)",
      personnelRecords:"FAC §65C-22.006(3)",
      childRecords:"FAC §65C-22.006(3)",
      hotWaterMax:"FAC §65C-22.003(1)(e)",
      toiletRatio:"FAC §65C-22.003(1)(d)",
      smokingProhibition:"FAC §65C-22.003; FS §386.204",
      coDetector:"FS §500.12; FAC §65C-22.003",
      fireDrill:"FAC §65C-22.004(1)(c)",
      tornadoDrill:"FAC §65C-22.004(1)(c)",
      fencing:"FAC §65C-22.003(2)(b)",
      insurance:"FS §402.305(2)(e)",
      inspPerYear:"FAC §65C-22.008"
    }
  },
  GA: { name:"Georgia", infant:6, toddler:8, preschool:15, schoolAge:18, indoorSqft:25, outdoorSqft:100, trainingHrs:10, inspPerYear:2, directorReq:"TCC in ECE, or CDA + 1 year experience", teacherReq:"High school diploma", qrs:"Quality Rated", agency:"GA Dept of Early Care and Learning", agencyPhone:"(404) 657-5562", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  ID: { name:"Idaho", infant:5, toddler:7, preschool:12, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:6, inspPerYear:1, directorReq:"No specific requirement; experience preferred", teacherReq:"Must be 18+; orientation required", qrs:"Idaho Stars (voluntary)", agency:"ID Dept of Health and Welfare", agencyPhone:"(208) 334-5700", insurance:"Not required", family:{familyCommunication:"No",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"120°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  IL: { name:"Illinois", infant:4, toddler:5, preschool:10, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"BA in ECE + 3 years experience, or AA + 5 years", teacherReq:"HS diploma + CDA", qrs:"ExceleRate Illinois", agency:"IL Dept of Children and Family Services", agencyPhone:"(217) 785-2509", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"3 years", workforceRegistry:"Gateways Registry (IL)", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  IN: { name:"Indiana", infant:4, toddler:5, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"AA in ECE or child development (or CDA + 1 year experience) + 1 year supervisory experience (470 IAC 3-4.7-18)", teacherReq:"High school diploma; orientation training", qrs:"Paths to QUALITY", agency:"IN Family and Social Services Administration", agencyPhone:"(800) 299-1627", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"IN Registry (Paths to QUALITY — FSSA)", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  KY: { name:"Kentucky", infant:5, toddler:6, preschool:12, schoolAge:14, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"CDA or 12 ECE credit hours + 1 year experience", teacherReq:"High school diploma; 1-hour orientation", qrs:"KIDS NOW", agency:"KY Cabinet for Health and Family Services", agencyPhone:"(502) 564-2524", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  LA: { name:"Louisiana", infant:5, toddlerTier1:7, toddlerTier1Ages:"12–24 months", toddlerTier2:8, toddlerTier2Ages:"24–36 months", preschool:14, schoolAge:20, indoorSqft:35, outdoorSqft:60, trainingHrs:12, inspPerYear:2, directorReq:"CDA + 2 years experience, or AA in ECE", teacherReq:"HS diploma or GED; 30-hour pre-service training", qrs:"Louisiana Quality Start", agency:"LA Dept of Education", agencyPhone:"(888) 524-3578", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious (LA RS 17:170 — philosophical exemption removed 2015)", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Monthly (shelter-in-place)", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"Louisiana Registry (LDOE — louisianaregistry.org)", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  MA: { name:"Massachusetts", infant:3, toddler:4, preschool:10, schoolAge:13, indoorSqft:33, outdoorSqft:75, trainingHrs:20, inspPerYear:1, directorReq:"BA in ECE or related + 2 years experience", teacherReq:"CDA or 12 ECE college credit hours", qrs:"MA QRIS", agency:"MA Dept of Early Education and Care", agencyPhone:"(617) 988-6600", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Required for subsidy", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"3 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"Annual", workforceRegistry:"MA ECE Workforce Registry", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  MD: { name:"Maryland", infant:3, toddler:6, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:16, inspPerYear:2, directorReq:"BA in ECE or related field + 3 years experience", teacherReq:"CDA or 90 clock hours of ECE training", qrs:"Maryland EXCELS", agency:"MD State Dept of Education", agencyPhone:"(410) 767-7805", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"MD Credentialing Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  MI: { name:"Michigan", infant:4, toddler:4, preschool:10, schoolAge:18, indoorSqft:35, outdoorSqft:60, trainingHrs:16, inspPerYear:1, directorReq:"BA in ECE or child development + 1 year experience", teacherReq:"Caregiver I credential (18 credit hours or CDA)", qrs:"Great Start to Quality", agency:"MI Dept of Licensing and Regulatory Affairs", agencyPhone:"(866) 685-0006", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Required for subsidy", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"MI Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  MN: { name:"Minnesota", infant:4, toddler:7, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:16, inspPerYear:1, directorReq:"BA in ECE or related + 2,080 hours of experience", teacherReq:"CDA or 12 ECE semester credit hours", qrs:"Parent Aware", agency:"MN Dept of Human Services", agencyPhone:"(651) 431-6500", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"MN Develop Registry", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  MS: { name:"Mississippi", infant:5, toddler:7, preschool:14, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"CDA + 2 years experience, or AA in ECE", teacherReq:"HS diploma or GED; 6-hour pre-employment orientation", qrs:"MS Star Quality Initiative", agency:"MS State Dept of Health", agencyPhone:"(601) 364-2827", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  NC: { name:"North Carolina", infant:5, toddler:6, preschool:10, schoolAge:15, indoorSqft:25, outdoorSqft:75, trainingHrs:12, inspPerYear:2, directorReq:"Administrator credential (AA ECE + 1yr, or BA + coursework)", teacherReq:"HS diploma; NC Childcare Credentials pathway", qrs:"NC Star Rated License (1-5 stars)", agency:"NC Dept of Health and Human Services", agencyPhone:"(919) 527-6335", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Required (star rating)", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"NC Nurturing Futures Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  NH: { name:"New Hampshire", infant:4, toddler:5, preschool:8, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:9, inspPerYear:1, directorReq:"BA in ECE + 2 years experience, or AA + 4 years", teacherReq:"HS diploma; 6 hours initial training", qrs:"NH QRIS", agency:"NH Dept of Health and Human Services", agencyPhone:"(603) 271-4624", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"120°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"NH Child Care Workforce Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  NJ: {
    name:"New Jersey",
    infant:4, toddler:6,
    preschoolTier1:10, preschoolTier1Ages:"2.5–4 years", preschoolTier1GroupMax:20,
    preschoolTier2:12, preschoolTier2Ages:"4–5 years", preschoolTier2GroupMax:24,
    schoolAge:15, schoolAgeGroupMax:30,
    indoorSqft:35, outdoorSqft:75, trainingHrs:20, trainingHrsFirstYear:100, inspPerYear:2,
    directorReq:"Any BA + 18 ECE/child development semester credits + 2 years experience in licensed child care or school setting (NJAC 3A:52-4.5(a))",
    teacherReq:"HS diploma + 6 ECE semester credits from accredited institution (NJAC 3A:52-4.6(a))",
    qrs:"Grow NJ Kids", agency:"NJ Dept of Children and Families", agencyPhone:"(800) 332-9227", insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"},
    rules:{
      fireDrillFreq:"Monthly",
      hotWaterMax:"110°F",
      fireSafetyTraining:"Yes",
      qrisType:"Voluntary",
      bgCheckType:"NJSP + FBI fingerprint + CARI check",
      tbTestReq:"Initial only",
      cprRenewal:"2 years",
      immExemptions:"Medical + Religious (NJSA 26:1A-9.1)",
      annualImmReporting:"Yes",
      recordRetention:"3 years",
      tornadoDrill:"2x/year",
      lockdownDrill:"2x/year",
      coDetector:"Required",
      mandatedReporterRenewal:"No renewal required (NJSA 9:6-8.10 — one-time at hire)",
      workforceRegistry:"NJ Registry for ECE and School-Age Professionals",
      staffPhysical:"Required at hire (within 30 days)",
      toiletRatio:"1:15",
      minFencingHeight:"4 ft"
    },
    refs:{
      ratios:"NJAC 3A:52-7.3(a)",
      indoorSqft:"NJAC 3A:52-5.3(a)",
      outdoorSqft:"NJAC 3A:52-5.3(b)",
      trainingHrs:"NJAC 3A:52-4.8 / 3A:52-4.9",
      directorReq:"NJAC 3A:52-4.5(a)",
      teacherReq:"NJAC 3A:52-4.6(a)",
      bgCheckType:"NJAC 3A:52-4.10 (NJSP + FBI + CARI)",
      immExemptions:"NJSA 26:1A-9.1; NJAC 3A:52-6.3",
      mandatedReporter:"NJSA 9:6-8.10; NJAC 3A:52-4.8",
      personnelRecords:"NJAC 3A:52-4.1(c)",
      childRecords:"NJAC 3A:52-4.1(c)",
      hotWaterMax:"NJAC 3A:52-5.4(c)",
      toiletRatio:"NJAC 3A:52-5.4(b)",
      smokingProhibition:"NJSA 26:3D-55 et seq.",
      coDetector:"NJSA 52:27D-198.4; NJAC 3A:52-5.4",
      fireDrill:"NJAC 3A:52-5.8(b)",
      tornadoDrill:"NJAC 3A:52-5.8(b)",
      fencing:"NJAC 3A:52-5.3(b)",
      insurance:"NJAC 3A:52-3.4",
      inspPerYear:"NJAC 3A:52-1.4"
    }
  },
  NM: { name:"New Mexico", infant:4, toddler:6, preschool:12, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:2, directorReq:"AA in ECE + 1 year experience, or CDA + 2 years", teacherReq:"HS diploma; 45-hour orientation", qrs:"NM FOCUS on Children (QRIS — NM CYFD)", agency:"NM Children, Youth and Families Dept", agencyPhone:"(505) 827-7499", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  NV: { name:"Nevada", infant:4, toddler:6, preschool:13, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"AA in ECE + 1 year, or CDA + 2 years experience", teacherReq:"HS diploma; pre-employment orientation", qrs:"Nevada Silver State Stars", agency:"NV Dept of Health and Human Services", agencyPhone:"(702) 486-7670", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"Annual (childcare staff)", workforceRegistry:"NV Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  NY: { name:"New York", infant:4, toddler:5, preschoolTier1:8, preschoolTier1Ages:"3–4 years", preschoolTier2:10, preschoolTier2Ages:"4–5 years", schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:2, directorReq:"BA in ECE + 2 years experience, or AA + 4 years", teacherReq:"CDA or AA in ECE", qrs:"QUALITYstarsNY", agency:"NY Office of Children and Family Services", agencyPhone:"(518) 474-9454", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State (DCJS) + FBI + SCR check (18 NYCRR §418-1.11)", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical only (PHL §2164)", annualImmReporting:"Yes", recordRetention:"3 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required (one-time — SSL §413)", workforceRegistry:"NY Aspire Registry", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  OH: { name:"Ohio", infant:5, toddler:7, preschool:12, schoolAge:18, indoorSqft:35, outdoorSqft:60, trainingHrs:20, inspPerYear:2, directorReq:"AA in ECE + 2 years experience, or BA in related", teacherReq:"HS diploma; 1-year experience working with children", qrs:"Step Up To Quality", agency:"OH Dept of Job and Family Services", agencyPhone:"(877) 302-2347", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Required for subsidy", bgCheckType:"State (BCI) + FBI fingerprint (ORC §5104.013)", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Quarterly", lockdownDrill:"Quarterly", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"OH Professional Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  OR: { name:"Oregon", infant:4, toddler:4, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"BA in ECE + 1 year, or AA + 3 years", teacherReq:"OCCRN Level 2 (HS diploma + 60 training hours)", qrs:"Oregon Spark QRIS", agency:"OR Dept of Early Learning and Care", agencyPhone:"(503) 947-1400", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"OR Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  PA: { name:"Pennsylvania", infant:4, toddler:6, preschool:10, schoolAge:12, indoorSqft:35, outdoorSqft:75, trainingHrs:18, inspPerYear:1, directorReq:"BA in ECE + 3 years experience, or AA + 5 years", teacherReq:"CDA or 30 college credits (6+ in ECE)", qrs:"Keystone STARS", agency:"PA Dept of Human Services", agencyPhone:"(717) 787-8691", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"3 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"5 years", workforceRegistry:"PA Early Learning Keys Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  SC: { name:"South Carolina", infant:6, toddler:8, preschool:13, schoolAge:18, indoorSqft:25, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"HS diploma + Director credential or equivalent", teacherReq:"HS diploma or GED; SCTOP orientation", qrs:"ABC Quality", agency:"SC Dept of Social Services", agencyPhone:"(803) 898-7327", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Education only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"SC Endeavors Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  TN: { name:"Tennessee", infant:5, toddler:7, preschool:13, schoolAge:18, indoorSqft:35, outdoorSqft:75, trainingHrs:18, inspPerYear:1, directorReq:"CDA or AA in ECE, or HS diploma + 3 years", teacherReq:"HS diploma; 40-hour orientation", qrs:"TN Star-Quality Child Care Program", agency:"TN Dept of Human Services", agencyPhone:"(615) 313-4778", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"TN TNPAL Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  TX: { name:"Texas", infant:4, toddler:9, preschool:15, schoolAge:26, indoorSqft:30, outdoorSqft:80, trainingHrs:12, inspPerYear:1,
    directorReq:"HS diploma + 6 ECE credit hours or CDA + 2 years experience (26 TAC §746.1309)",
    teacherReq:"HS diploma or GED + 8-hour orientation (26 TAC §746.1303)",
    qrs:"Texas Rising Star", agency:"TX Health and Human Services Commission", agencyPhone:"(800) 862-5252", insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"},
    rules:{
      fireDrillFreq:"Monthly",
      hotWaterMax:"110°F",
      fireSafetyTraining:"Yes",
      qrisType:"Voluntary",
      bgCheckType:"State + FBI fingerprinting",
      tbTestReq:"Initial only (risk-based)",
      cprRenewal:"2 years",
      immExemptions:"Medical + Religious (TX Health & Safety Code §161.004)",
      annualImmReporting:"Yes",
      recordRetention:"2 years",
      tornadoDrill:"Monthly",
      lockdownDrill:"2x/year",
      coDetector:"Required",
      mandatedReporterRenewal:"No renewal required (TX Family Code §261.101 — one-time at hire)",
      workforceRegistry:"TX Workforce Registry",
      staffPhysical:"Required at hire",
      toiletRatio:"1:15 (1 toilet per 15 children)",
      toddlerRatioYoung:"1:5 (12–17 months)",
      toddlerRatioOlder:"1:9 (18–35 months)",
      minFencingHeight:"4 ft"
    },
    refs:{
      ratios:"26 TAC §746.1601",
      indoorSqft:"26 TAC §746.3405",
      outdoorSqft:"26 TAC §746.3407",
      trainingHrs:"26 TAC §746.1301",
      directorReq:"26 TAC §746.1309",
      teacherReq:"26 TAC §746.1303",
      bgCheckType:"26 TAC §746.1209",
      staffPhysical:"26 TAC §746.1205",
      tbTestReq:"26 TAC §746.1205",
      cprRenewal:"26 TAC §746.1303",
      childRecords:"26 TAC §746.801",
      hotWaterMax:"26 TAC §746.3417",
      toiletRatio:"26 TAC §746.3503",
      fencing:"26 TAC §746.3415",
      drills:"26 TAC §746.3701",
      coDetector:"26 TAC §746.3301",
      insurance:"26 TAC §746.203",
      immExemptions:"TX Health & Safety Code §161.004",
      mandatedReporter:"TX Family Code §261.101"
    }
  },

  VA: {
    name:"Virginia",
    infant:4, toddler:5, preschool:10, schoolAge:18,
    indoorSqft:35, outdoorSqft:75, trainingHrs:16, inspPerYear:2,
    directorReq:"BA in ECE or related field + experience per 8VAC20-780 qualification pathways",
    teacherReq:"HS diploma + health & safety training (8VAC20-780-240)",
    qrs:"VQB5 — Virginia Quality", agency:"VA Dept of Education — Office of Child Care Health and Safety (OCCHS)", agencyPhone:"(833) 778-0204", insurance:"Required",
    family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"},
    rules:{
      fireDrillFreq:"Monthly",
      hotWaterMax:"110°F",
      fireSafetyTraining:"Yes",
      qrisType:"Voluntary",
      bgCheckType:"Criminal history + sex offender registry + child abuse/neglect registry — Fieldprint (fingerprint, from Jan 1 2026)",
      tbTestReq:"At hire + renewal every 2 years (8VAC20-780-160)",
      cprRenewal:"2 years",
      immExemptions:"Medical + Religious",
      annualImmReporting:"Yes",
      recordRetention:"2 years",
      tornadoDrill:"Not required",
      lockdownDrill:"2x/year",
      coDetector:"Required",
      mandatedReporterRenewal:"No renewal required (one-time at hire — 8VAC20-780-240)",
      workforceRegistry:"VA ECE Workforce Registry",
      staffPhysical:"Required at hire",
      toiletRatio:"1:15",
      minFencingHeight:"4 ft"
    },
    refs:{
      ratios:"8VAC20-780",
      indoorSqft:"8VAC20-780-310",
      outdoorSqft:"8VAC20-780-310",
      trainingHrs:"8VAC20-780-240",
      directorReq:"8VAC20-780-180 to 8VAC20-780-220",
      teacherReq:"8VAC20-780-240",
      bgCheckType:"8VAC20-780-70 (Fieldprint — criminal + sex offender + child abuse registry)",
      immExemptions:"8VAC20-780-130",
      mandatedReporter:"8VAC20-780-240",
      personnelRecords:"8VAC20-780-50(b)",
      childRecords:"8VAC20-780-60",
      hotWaterMax:"8VAC20-780",
      toiletRatio:"8VAC20-780",
      tbTestReq:"8VAC20-780-160 (at hire + 2-yr renewal)",
      fireDrill:"8VAC20-780-560",
      lockdownDrill:"8VAC20-780-560",
      drinkingWater:"Code of VA §22.1-289.057 (from Jan 1 2025)"
    }
  },
  WA: { name:"Washington", infant:4, toddler:7, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:20, inspPerYear:1, directorReq:"BA in ECE + 2 years, or AA + 4 years", teacherReq:"Short certificate in ECE (20 credits) or CDA", qrs:"Early Achievers", agency:"WA Dept of Children, Youth and Families", agencyPhone:"(866) 482-4325", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Required for subsidy", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"WA DEL Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"48 in (4 ft)"} },
  WI: { name:"Wisconsin", infant:4, toddler:6, preschool:13, schoolAge:18, indoorSqft:35, outdoorSqft:60, trainingHrs:25, inspPerYear:1, directorReq:"Technical diploma or AA in ECE, or CDA + experience", teacherReq:"HS diploma; Wisconsin Registry requirement", qrs:"YoungStar", agency:"WI Dept of Children and Families", agencyPhone:"(608) 266-9939", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"WI Registry", staffPhysical:"Required at hire (initial only)", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  AK: { name:"Alaska", infant:5, toddler:6, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"AA in ECE or related field + 1 year experience", teacherReq:"HS diploma + 6 ECE credit hours or CDA; must be 18+", qrs:"Alaska SEED (voluntary)", agency:"AK Dept of Health and Social Services", agencyPhone:"(907) 334-2200", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  AR: { name:"Arkansas", infant:6, toddler:9, preschool:15, schoolAge:20, indoorSqft:35, outdoorSqft:60, trainingHrs:12, inspPerYear:1, directorReq:"HS diploma + Child Care Director credential or CDA + 2 years experience", teacherReq:"HS diploma or GED; orientation training required", qrs:"Better Beginnings (voluntary)", agency:"AR Dept of Human Services", agencyPhone:"(501) 682-8590", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Monthly", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  DE: { name:"Delaware", infant:4, toddler:6, preschool:12, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:2, directorReq:"BA in ECE or related + 2 years experience, or AA + 4 years", teacherReq:"CDA or 12 ECE college credits; HS diploma required", qrs:"Delaware Stars for Early Success", agency:"DE Office of Child Care Licensing", agencyPhone:"(302) 892-5800", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Delaware Stars", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"DE ECE Workforce Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  HI: { name:"Hawaii", infant:4, toddler:6, preschool:10, schoolAge:16, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"BA in ECE or related field + 2 years experience", teacherReq:"CDA or AA in ECE; HS diploma required", qrs:"Preschool Open Doors (voluntary)", agency:"HI Dept of Human Services", agencyPhone:"(808) 586-5767", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"HI PCDP Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  IA: { name:"Iowa", infant:4, toddler:6, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"AA in ECE + 1 year experience, or CDA + 3 years experience", teacherReq:"HS diploma; 16-hour health & safety training", qrs:"Quality Preschool Program (voluntary)", agency:"IA Dept of Health and Human Services", agencyPhone:"(515) 281-5521", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Monthly", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"3 years", workforceRegistry:"IA COMPASS Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  KS: { name:"Kansas", infant:3, toddler:6, preschool:12, schoolAge:18, indoorSqft:35, outdoorSqft:75, trainingHrs:6, inspPerYear:1, directorReq:"HS diploma + 12 ECE credit hours or CDA + 2 years experience", teacherReq:"Must be 18+; HS diploma preferred; orientation required", qrs:"Kansas Child Care Training Opportunities (voluntary)", agency:"KS Dept for Children and Families", agencyPhone:"(785) 296-1270", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Monthly", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"KS ECE Workforce Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  ME: { name:"Maine", infant:4, toddler:6, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:24, inspPerYear:1, directorReq:"BA in ECE + 2 years, or AA + 4 years, or CDA + 5 years", teacherReq:"HS diploma + CDA or 12 ECE credit hours", qrs:"Quality for ME (voluntary)", agency:"ME Dept of Health and Human Services", agencyPhone:"(207) 624-7900", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"4 years", workforceRegistry:"ME Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  MO: { name:"Missouri", infant:4, toddler:8, preschool:10, schoolAge:20, indoorSqft:35, outdoorSqft:60, trainingHrs:12, inspPerYear:1, directorReq:"AA in ECE + 1 year, or HS diploma + CDA + 2 years", teacherReq:"HS diploma or GED; orientation required", qrs:"Missouri Quality Stars (voluntary)", agency:"MO Dept of Health and Senior Services", agencyPhone:"(573) 751-2450", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Quarterly", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"MO Open DOORS Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  MT: { name:"Montana", infant:4, toddler:8, preschool:10, schoolAge:14, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"HS diploma + CDA or 12 ECE credit hours + 1 year experience", teacherReq:"Must be 18+; HS diploma or GED; orientation training", qrs:"Quality Stars MT (voluntary)", agency:"MT Dept of Public Health and Human Services", agencyPhone:"(406) 444-5900", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  ND: { name:"North Dakota", infant:4, toddler:7, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:9, inspPerYear:1, directorReq:"AA in ECE or CDA + 1 year experience", teacherReq:"HS diploma; must be 18+; 6-hour orientation", qrs:"Spark ND (voluntary)", agency:"ND Dept of Health and Human Services", agencyPhone:"(701) 328-2316", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious + Philosophical", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"ND Afterschool & ECE Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  NE: { name:"Nebraska", infant:4, toddler:6, preschool:12, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:18, inspPerYear:1, directorReq:"AA in ECE + 2 years, or CDA + 3 years", teacherReq:"HS diploma + CDA or 12 ECE college credits", qrs:"Step Up to Quality NE (voluntary)", agency:"NE Dept of Health and Human Services", agencyPhone:"(402) 471-9278", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Monthly", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"NE Shines Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  OK: { name:"Oklahoma", infant:4, toddler:6, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:2, directorReq:"AA in ECE or CDA + 2 years experience", teacherReq:"HS diploma or GED; orientation training required", qrs:"Reaching for the Stars (voluntary)", agency:"OK Dept of Human Services", agencyPhone:"(405) 522-5050", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"Monthly", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"OK Pathway to Career Excellence", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  RI: { name:"Rhode Island", infant:4, toddler:6, preschool:9, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:20, inspPerYear:1, directorReq:"BA in ECE or related + 2 years, or AA + 3 years", teacherReq:"CDA or 12 ECE college credits; HS diploma required", qrs:"BrightStars Rhode Island", agency:"RI Dept of Human Services", agencyPhone:"(401) 462-2003", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"RI ECERS Registry", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  SD: { name:"South Dakota", infant:5, toddler:10, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:12, inspPerYear:1, directorReq:"HS diploma + CDA or relevant experience; no specific degree required", teacherReq:"Must be 18+; HS diploma; orientation required", qrs:"South Dakota Stars (voluntary)", agency:"SD Dept of Social Services", agencyPhone:"(605) 773-4766", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"No", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  UT: { name:"Utah", infant:4, toddler:7, preschool:12, schoolAge:20, indoorSqft:35, outdoorSqft:75, trainingHrs:20, inspPerYear:1, directorReq:"AA in ECE + 1 year, or CDA + 2 years", teacherReq:"HS diploma or GED; 20-hour orientation training", qrs:"Child Care Quality Program UT (voluntary)", agency:"UT Dept of Health and Human Services", agencyPhone:"(801) 538-4242", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"UT ECE Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  VT: { name:"Vermont", infant:4, toddler:5, preschool:10, schoolAge:12, indoorSqft:35, outdoorSqft:75, trainingHrs:30, inspPerYear:1, directorReq:"BA in ECE or related + 2 years; strictest requirements nationally", teacherReq:"AA in ECE or 12 ECE credits + 1 year experience; CDA accepted", qrs:"Vermont STARS (voluntary)", agency:"VT Dept for Children and Families", agencyPhone:"(800) 649-2642", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"Yes"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"Not required", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"VT WAGE$ Registry", staffPhysical:"Required at hire", toiletRatio:"1:10", minFencingHeight:"4 ft"} },
  WV: { name:"West Virginia", infant:4, toddler:7, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:15, inspPerYear:1, directorReq:"AA in ECE + 2 years, or CDA + 3 years", teacherReq:"HS diploma + CDA or 12 ECE college credits", qrs:"West Virginia ECEEC (voluntary)", agency:"WV Dept of Human Services", agencyPhone:"(304) 558-7980", insurance:"Required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"2 years", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required", mandatedReporterRenewal:"No renewal required", workforceRegistry:"WV STARS Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
  WY: { name:"Wyoming", infant:4, toddler:10, preschool:10, schoolAge:15, indoorSqft:35, outdoorSqft:75, trainingHrs:10, inspPerYear:1, directorReq:"HS diploma + CDA or equivalent; no specific degree required", teacherReq:"Must be 18+; HS diploma or GED", qrs:"Wyoming Shine (voluntary)", agency:"WY Dept of Family Services", agencyPhone:"(307) 777-3693", insurance:"Not required", family:{familyCommunication:"Yes",writtenPolicies:"Yes",careLog:"Yes",familyMeetings:"No"}, rules:{fireDrillFreq:"Monthly", hotWaterMax:"110°F", fireSafetyTraining:"Yes", qrisType:"Voluntary", bgCheckType:"State + FBI", tbTestReq:"Initial only", cprRenewal:"2 years", immExemptions:"Medical + Religious", annualImmReporting:"Yes", recordRetention:"1 year", tornadoDrill:"2x/year", lockdownDrill:"2x/year", coDetector:"Required (building code)", mandatedReporterRenewal:"No renewal required", workforceRegistry:"WY STARS Registry", staffPhysical:"Required at hire", toiletRatio:"1:15", minFencingHeight:"4 ft"} },
};

export function getReg(state) {
  return STATE_REGS[state] || STATE_REGS['TX'];
}

// ── Formatted reg object for UI consumption ───────────────────────────────────
export function getRegForUI(state) {
  const r = STATE_REGS[state] || STATE_REGS['TX'];
  const ru = r.rules || {};
  return {
    agency:      r.agency      || 'State Childcare Licensing',
    agencyPhone: r.agencyPhone || '',
    citation:    r.citation    || state,
    qrisName:    r.qrs         || 'Quality Rating System',
    refs:        r.refs        || {},   // statutory section references (CA, DC, TX, FL, NJ, VA)
    rules: {
      infantRatio:    `1:${r.infant}`,
      toddlerRatio:   `1:${r.toddler}`,
      preschoolRatio: `1:${r.preschool}`,
      schoolAgeRatio: `1:${r.schoolAge}`,
      indoorSqft:     r.indoorSqft,
      outdoorSqft:    r.outdoorSqft,
      trainingHours:  r.trainingHrs,
      inspPerYear:    r.inspPerYear,
      fencingMin:     parseInt(ru.minFencingHeight) || 4,
      hotWaterMax:    parseInt(ru.hotWaterMax) || 110,
      toiletRatio:    parseInt((ru.toiletRatio||'1:15').split(':')[1]) || 15,
      fireDrillFreq:  ru.fireDrillFreq    || 'Monthly',
      tornadoDrillFreq: ru.tornadoDrill   || 'Monthly',
      cprRenewal:     ru.cprRenewal       || 'Every 2 years',
      bgCheck:        ru.bgCheckType      || 'State + FBI',
      mandatedReporterRenewal: ru.mandatedReporterRenewal || 'Required',
      workforceRegistry: ru.workforceRegistry || 'Check state',
      qrisName:       r.qrs || '',
      recordRetention: ru.recordRetention || '2',
    }
  };
}
